version: '3'
name: tendex-prod

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
    # env_file:
    #   - "frontend/.env"
    network_mode: bridge
    restart: always
  database:
    image: postgres:15.2
    volumes:
    - "./database/data:/var/lib/postgresql/data"
    env_file:
      - "database/.env"
    ports:
      - "5432:5432"
    network_mode: bridge
    restart: always

# docker compose up -d